#pragma once

#include "failed/Compilation.hpp"
#include "failed/CompilerVersionQuery.hpp"
#include "failed/ParseSystemIncludes.hpp"
#include "failed/FileOpen.hpp"
#include "failed/FileSystem.hpp"
#include "failed/Linking.hpp"
#include "invalid/Argument.hpp"
#include "invalid/CircularDependency.hpp"
#include "missing/Configuration.hpp"
#include "missing/Dependency.hpp"
#include "unsupported/CompilerVersion.hpp"
#include "unsupported/Cast.hpp"
#include "violated/Assertion.hpp"